"""initial_all_tables

Revision ID: 7beb3381c931
Revises: 
Create Date: 2026-06-27 22:40:39.087082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7beb3381c931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_token', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Token 名称',
               existing_comment='Token 名称，如"我的开发环境"',
               existing_nullable=False)
    op.alter_column('api_token', 'token',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               comment='JWT Token 字符串',
               existing_comment='Token 字符串',
               existing_nullable=False)
    op.alter_column('api_token', 'jti',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='JWT ID，用于撤销',
               existing_comment='JWT ID，用于 Redis 黑名单撤销')
    op.alter_column('api_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='过期时间',
               existing_comment='过期时间，空=永不过期',
               existing_nullable=True)
    op.drop_constraint('api_token_jti_unique', 'api_token', type_='unique')
    op.create_index(op.f('ix_api_token_jti'), 'api_token', ['jti'], unique=True)
    op.alter_column('chat_message', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='user / assistant',
               existing_nullable=False)
    op.alter_column('chat_message', 'id',
               existing_type=sa.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_message', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment='备注',
               existing_nullable=True)
    op.alter_column('chat_message', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='状态：True=启用，False=禁用',
               existing_server_default=sa.text('true'))
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'chat_message',
        existing_comment='AI 助手聊天记录',
        schema=None
    )
    op.alter_column('node_service', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='服务版本号，如 v1.0.0',
               existing_nullable=True)
    op.alter_column('node_service', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='服务参数定义 [{field,label,type,required,description}]',
               existing_nullable=True)
    op.alter_column('node_service', 'original_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='节点原始参数备份，仅首次创建时写入，用于恢复',
               existing_nullable=True)
    op.alter_column('node_service', 'timeout',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='任务超时时间（秒），默认60秒。≤60秒同步返回，>60秒异步返回task_id',
               existing_comment='任务超时时间（秒），默认300秒=5分钟',
               existing_server_default=sa.text('300'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_service', 'timeout',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='任务超时时间（秒），默认300秒=5分钟',
               existing_comment='任务超时时间（秒），默认60秒。≤60秒同步返回，>60秒异步返回task_id',
               existing_server_default=sa.text('300'))
    op.alter_column('node_service', 'original_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='节点原始参数备份，仅首次创建时写入，用于恢复',
               existing_nullable=True)
    op.alter_column('node_service', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='服务参数定义 [{field,label,type,required,description}]',
               existing_nullable=True)
    op.alter_column('node_service', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='服务版本号，如 v1.0.0',
               existing_nullable=True)
    op.create_table_comment(
        'chat_message',
        'AI 助手聊天记录',
        existing_comment=None,
        schema=None
    )
    op.alter_column('chat_message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_message', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='状态：True=启用，False=禁用',
               existing_server_default=sa.text('true'))
    op.alter_column('chat_message', 'remark',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('chat_message', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat_message', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='user / assistant',
               existing_nullable=False)
    op.drop_index(op.f('ix_api_token_jti'), table_name='api_token')
    op.create_unique_constraint('api_token_jti_unique', 'api_token', ['jti'])
    op.alter_column('api_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='过期时间，空=永不过期',
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('api_token', 'jti',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='JWT ID，用于 Redis 黑名单撤销',
               existing_comment='JWT ID，用于撤销')
    op.alter_column('api_token', 'token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               comment='Token 字符串',
               existing_comment='JWT Token 字符串',
               existing_nullable=False)
    op.alter_column('api_token', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Token 名称，如"我的开发环境"',
               existing_comment='Token 名称',
               existing_nullable=False)
    # ### end Alembic commands ###
